In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

2025-04-08 09:01:52.557216: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
import pandas_ta as ta

In [5]:
market =pd.read_csv('../data/processed-data/price-gold.csv', index_col='Date',  parse_dates=True)
market.drop('Change %', axis=1, inplace=True)
market.head(20)

Close    Open    High     Low      Vol.
Date                                                
2015-01-02  1186.2  1184.0  1194.9  1167.3  120680.0
2015-01-05  1204.0  1187.8  1207.5  1177.8  149110.0
2015-01-06  1219.4  1204.0  1223.3  1201.6  190360.0
2015-01-07  1210.7  1219.0  1219.4  1209.1  117090.0
2015-01-08  1208.5  1211.0  1216.8  1204.2  122490.0
2015-01-09  1216.1  1208.9  1224.0  1207.0  155980.0
2015-01-12  1232.8  1223.0  1236.0  1217.5  138520.0
2015-01-13  1234.4  1233.1  1244.5  1227.4  179650.0
2015-01-14  1234.5  1231.2  1244.6  1224.9  193110.0
2015-01-15  1264.8  1229.7  1267.2  1226.1  288790.0
2015-01-16  1276.9  1263.5  1282.4  1255.2  219410.0
2015-01-19  1294.2  1280.7  1297.2  1272.1  249780.0
2015-01-21  1293.7  1295.3  1307.0  1284.6  210390.0
2015-01-22  1300.7  1293.7  1307.8  1279.1  214910.0
2015-01-23  1292.6  1301.5  1302.9  1284.3  149210.0
2015-01-26  1279.4  1292.8  1299.2  1275.6  168890.0
2015-01-27  1291.7  1280.7  1297.4  1272.0  186950.0
2015-01-28  1285.9  1292.0  1293.3  1279.0  180390.0
2015-01-29  1255.9  1284.0  1286.6  1252.1  243650.0
2015-01-30  1279.2  1259.0  1285.4  1257.5  163880.0

In [6]:
atr_period = 14
market["ATR"] = ta.atr(market["High"], market["Low"], market["Close"], length=atr_period)

In [7]:
def create_sequences(data, lookback):
        X, y = [], []
        for i in range(lookback, len(data)-6):
            X.append(data[i - lookback:i])
            y.append(data[i:i+6, 1])  # Predict the 'Close' price (index 1)
        return np.array(X), np.array(y)

In [8]:
from joblib import load

model = tf.keras.models.load_model('../models/model1/lstm_model.keras')
scaler = load('../models/model1/scaler.save')

/home/elm19/miniconda3/envs/goldspot-predictor/lib/python3.11/site-packages/keras/src/saving/saving_lib.py:719: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 10 variables whereas the saved optimizer has 18 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


In [12]:

class trade:
    def __init__(self, market, model, scaler, lookback_period=10):
        self.market = market
        self.data = market[['Open', 'Close', 'High', 'Low', 'Vol.']].copy()
        self.scaled_data = scaler.transform(self.data)
        self.model = model
        self.scaler = scaler
        self.lookback_period = lookback_period
        self.X, self.y = create_sequences(self.scaled_data, lookback_period)

    def inverse_transform(self, data):
        # Inverse transform the predictions
        predicted_inv = np.zeros((data.shape[0], data.shape[1]))
        for i in range(data.shape[1]):
            dummy_predictions = np.zeros((len(data), 5))
            dummy_predictions[:, 1] = data[:, i]
            predicted_inv[:, i] = scaler.inverse_transform(dummy_predictions)[:, 1]


        return predicted_inv
    
    def backtest(self):
        X_backtest = np.reshape(self.X, (self.X.shape[0], self.X.shape[1], self.X.shape[2]))
        predictions = self.model.predict(X_backtest)
        
        print(predictions, predictions.shape)
        print('-------------------------------')

        # Inverse transform the predictions
        predictions = self.inverse_transform(predictions)

        reely = self.inverse_transform(self.y)

        print(predictions, predictions.shape)
        print('-------------------------------')
        print(reely, reely.shape)

        
        # Simulate trading logic here
        # for i, (index, row) in enumerate(self.market.iterrows()):
        #     # Example trading logic: buy if the model predicts a price increase
        #     past_six = self.market.iloc[i-6:i]
        #     if i < 6 or i<self.lookback_period or i >= len(predictions) or i < atr_period:
        #         continue

        #     print(row)
        #     print(reely[i + max(self.lookback_period, atr_period)])
        #     print(predictions[i + max(self.lookback_period, atr_period)])

            
            # # # Example: Check if the predicted price is higher than the atr
            # if predictions[i + max(self.lookback_period, atr_period)].any() > row["ATR"]:
            #     print(f"Buying at {row['Close']} on {index}")
            # else:
            #     print(f"Selling at {row['Close']} on {index}")
            # ma_6day = past_six["Close"].mean()
            # print(f"Date: {index}, 6-day MA: {ma_6day:.2f}")


In [13]:

trade_instance = trade(market, model, scaler, lookback_period=10)
trade_instance.backtest()

72/72 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step
[[0.20167476 0.2013141  0.2008776  0.193597   0.19779226 0.19948085]
 [0.2217632  0.22102824 0.22020285 0.21141113 0.21540955 0.21693377]
 [0.24112023 0.24019586 0.23907909 0.2291762  0.23252505 0.23387371]
 ...
 [0.98662674 0.98565376 0.9750295  0.96007353 0.9649218  0.9604115 ]
 [1.0013678  1.0007008  0.9886468  0.9744254  0.97845185 0.9726896 ]
 [0.9675285  0.9674787  0.95917845 0.94463867 0.95183957 0.94705975]] (2300, 6)
-------------------------------
[[1258.11153373 1257.7386548  1257.28735774 1249.75994225 1254.09741952
  1255.84324722]
 [1278.88096587 1278.12109582 1277.26772487 1268.17797083 1272.31193074
  1273.88782684]
 [1298.89421007 1297.938495   1296.78386905 1286.54526643 1290.00764986
  1291.40202881]
 ...
 [2069.6733909  2068.66742045 2057.68302915 2042.22002336 2047.23262057
  2042.56943849]
 [2084.91417606 2084.2245896  2071.76193199 2057.05839569 2061.22136568
  2055.26380701]
 [2049.92773891 2049.87622021 2041.2945971  2026.